# Base chance for item duplication (dupes.use).
# This value should be between 0 and 100, representing the percentage chance of success.
# For example, 50 means a 50% chance of duplication.
dupe-chance: 1.0

# Whether to send messages when items are duplicated
enable-messages: true

# Whether to require permission to use dupe
require-permission: true

# Enable or disable specific logs
log-successful-duplications: true