name: DupeS
version: ${project.version} # Maven handles this
# Correct main class path to match FIXED package and class name
main: com.rafalohaki.DupeS.DupeS
description: A simple plugin to duplicate items from item frames.
author: Rafalohaki
api-version: 1.21

commands:
  dupe:
    description: Admin commands for DupeS plugin.
    usage: /dupe <reload|help>
    aliases: [duplication]
    permission: dupes.admin

permissions:
  dupes.use:
    description: Allows players to duplicate items by interacting with item frames.
    default: false
  dupes.admin:
    description: Allows access to admin commands like /dupe reload.
    default: op