name: DupeS
version: '${project.version}'
main: com.rafalohaki.dupe.DupeS
api-version: '1.21'
author: rafalohaki
description: Item frame duplication plugin

commands:
  dupereload:
    description: Reloads the DupeS configuration
    usage: /dupereload
    permission: dupes.reload

permissions:
  dupes.use:
    description: "Allows the use of the dupe feature."
    default: false
  dupes.vip:
    description: "Grants VIP access to enhanced dupe features."
    default: false
  dupes.reload:
    description: "Allows reloading of the DupeS plugin configuration."
    default: op