name: DupeS
version: ${project.version}
main: com.rafalohaki.dupe.DupeS
description: A simple plugin to duplicate items from item frames.
author: Rafalohaki
api-version: 1.18

commands:
  dupereload:
    description: Reload the DupeS plugin configuration.
    usage: /<command>
    permission: dupes.reload

permissions:
  dupes.use:
    description: "Allows the player to use the duplication feature."
    default: false

  dupes.vip:
    description: "Grants VIP duplication chances."
    default: false

  dupes.reload:
    description: "Allows reloading the DupeS plugin configuration."
    default: op
