name: DupeS
version: ${project.version}
main: com.rafalohaki.dupe.DupeS
description: A simple plugin to duplicate items from item frames.
author: Rafalohaki
api-version: 1.21

commands:
  dupe:
    description: Admin commands for DupeS plugin.
    usage: /dupe <subcommand>
    aliases: [duplication]
    permission: dupes.admin
    subcommands:
      reload:
        description: Reload the DupeS plugin configuration.
        usage: /dupe reload
        permission: dupes.admin

permissions:
  dupes.use:
    description: Allows players to duplicate items.
    default: false # Changed to false by default
  dupes.admin:
    description: Allows access to admin commands for the plugin.
    default: op